spring:
  profiles: docker
  
server:
  port: ${SERVICE_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true  
    service-url:
      defaultZone: ${REGISTRY_URL}      